Client error for data analysis error
Causes http test to fail as it should

2019/04/08 18:03:09 GetAnalysis failed to get query
2019/04/08 18:03:09 select "field_json", count(*) qty from "public"."DataTypeTest" group by "field_json" order by count(*) desc, "field_json" limit 100;
2019/04/08 18:03:09 pq: could not identify an ordering operator for type json
2019/04/08 18:03:09 error rendering table analysis: pq: could not identify an ordering operator for type json
--- FAIL: Test_Http (0.14s)
    sse_test.go:894: 500 status for /tables/public.DataTypeTest/analyse-data, expected 200
FAIL